project:
  type: website
  output-dir: docs

website:
  title: "Thomas Arocena"
  image: man/figure/logo.png
  favicon: man/figures/logo.png
  open-graph: true
  navbar:
    logo: man/figures/logo.png
    left:
      - href: index.qmd
        text: Home
        

format:
  html:
    theme: lumen
    toc: true



