project:
  type: website
  output-dir: docs

website:
  title: "Thomas Arocena"
  description: "Étudiant ingénieur (Mines Nancy) et en M2 Mathématiques fondamentales et appliquées"
  site-url: "https://thomas-arocena.github.io/ThomasAROCENAwebpage/"
  image: man/figures/logo.png
  favicon: man/figures/logo.png
  open-graph: true
  navbar:
    logo: man/figures/logo.png
    left:
      - href: index.qmd
        text: Home
        

format:
  html:
    theme: lumen
    toc: true
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="B8eNMsIupuFgkOLhe2UmZ-XE0_OrV1fGdeWwZl_juJc" />



